version: '3'
services:
  frontend:
   container_name: frontend
   build:
    context: ./client
    dockerfile: Dockerfile
   ports:
     - 3000:3000
   stdin_open: true
   networks:
      frontend-tier-network:
        ipv4_address: 172.128.0.3
  backend:
   container_name: backend
   build:
    context: ./backend
    dockerfile: Dockerfile
   ports:
     - "5050:5050"
   environment:
    PORT: 5050
    MONGO_URI: 'mongodb://francis:francis@172.127.0.1:27017'
   depends_on:
      - mongo
   networks:
      backend-tier-network:
        ipv4_address: 172.127.0.2
      frontend-tier-network:
        ipv4_address: 172.128.0.2
  mongo:
    container_name: database
    image: mongo
    ports:
      - 27017:27017
    networks:
      backend-tier-network:
        ipv4_address: 172.127.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: francis
      MONGO_INITDB_ROOT_PASSWORD: francis
networks:
  frontend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.128.0.0/16
  backend-tier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.127.0.0/16
